import { createClient } from '@/lib/supabase/server';
import type { Database, QrCode } from '@/types/database';

type QrCodeInsert = Database['public']['Tables']['qr_codes']['Insert'];

/**
 * Insert a new QR code record for a property (and optionally a specific unit).
 * The `short_code` and `portal_url` must be generated by the caller before insertion.
 */
export async function createQrCode(
  propertyId: string,
  unitId: string | null,
  data: Omit<QrCodeInsert, 'property_id' | 'unit_id'>
): Promise<{
  data: QrCode | null;
  error: string | null;
}> {
  try {
    const supabase = await createClient();
    const { data: qrCode, error } = await supabase
      .from('qr_codes')
      .insert({
        ...data,
        property_id: propertyId,
        unit_id: unitId,
      })
      .select()
      .single();

    if (error) throw error;
    return { data: qrCode as QrCode, error: null };
  } catch (err) {
    console.error('createQrCode error:', err);
    return { data: null, error: (err as Error).message };
  }
}

/**
 * Look up a QR code record by its short code.
 * Used when a prospect scans a QR code to resolve the target property/unit.
 */
export async function getQrCode(shortCode: string): Promise<{
  data: QrCode | null;
  error: string | null;
}> {
  try {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from('qr_codes')
      .select('*')
      .eq('short_code', shortCode)
      .eq('is_active', true)
      .single();

    if (error) throw error;
    return { data: data as QrCode, error: null };
  } catch (err) {
    console.error('getQrCode error:', err);
    return { data: null, error: (err as Error).message };
  }
}

/**
 * Fetch all QR codes for a specific property, ordered by creation date.
 */
export async function getQrCodesByProperty(propertyId: string): Promise<{
  data: QrCode[] | null;
  error: string | null;
}> {
  try {
    const supabase = await createClient();
    const { data, error } = await supabase
      .from('qr_codes')
      .select('*')
      .eq('property_id', propertyId)
      .order('created_at');

    if (error) throw error;
    return { data: data as QrCode[], error: null };
  } catch (err) {
    console.error('getQrCodesByProperty error:', err);
    return { data: null, error: (err as Error).message };
  }
}

/**
 * Increment the scan count for a QR code and update the last scanned timestamp.
 * Called each time a prospect scans the code at a property.
 */
export async function incrementScanCount(shortCode: string): Promise<{
  data: QrCode | null;
  error: string | null;
}> {
  try {
    const supabase = await createClient();

    // Fetch current count first
    const { data: current, error: fetchError } = await supabase
      .from('qr_codes')
      .select('id, scan_count')
      .eq('short_code', shortCode)
      .single();

    if (fetchError) throw fetchError;
    if (!current) throw new Error('QR code not found');

    // Increment and update last scanned timestamp
    const { data, error } = await supabase
      .from('qr_codes')
      .update({
        scan_count: current.scan_count + 1,
        last_scanned_at: new Date().toISOString(),
      })
      .eq('id', current.id)
      .select()
      .single();

    if (error) throw error;
    return { data: data as QrCode, error: null };
  } catch (err) {
    console.error('incrementScanCount error:', err);
    return { data: null, error: (err as Error).message };
  }
}
